const locationKeywords = [
  'San Francisco',
  'SF',
  'Bay Area',
  'Golden Gate',
  'Alcatraz',
  "Fisherman's Wharf",
  'Cable cars',
  'Silicon Valley',
  'Tech industry',
  'Salesforce Tower',
  'Chinatown',
  'Mission District',
  'Golden Gate Park',
  'Fog City',
  'City by the Bay',
  'Transamerica Pyramid',
  'Pier 39',
  'Painted Ladies',
  'Coit Tower',
  'San Francisco Giants',
  'SF Giants',
  '49ers',
  'San Francisco 49ers',
  'Castro District',
  'Haight-Ashbury',
  'Treasure Island',
  'Twin Peaks',
  'Yerba Buena Gardens',
  'Presidio',
  'Embarcadero',
  'Oracle Park',
  'Bay Bridge',
  'California Street',
  'Lombard Street',
  'Ghirardelli Square',
  'Baker Beach',
  'Ocean Beach',
  'Sutro Baths',
  'Cliff House',
  'San Francisco Zoo',
  'Fort Mason',
  'Exploratorium',
]

const techKeywords = []

export { locationKeywords, techKeywords }
